/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

/* Functionality:
 * Toggle LED on PA13 on having EXTI0
 * PA.0 >> EXTI0 >> NVIC >> CPU
*/

/* Registers */
/* RCC */
#define RCC_BASE     0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0x18)
/* NVIC */
#define NVIC_ISER0   *(volatile uint32_t*)(0xE000E100 + 0x00)
/* GPIO */
#define GPIOA_BASE	 0x40010800
#define GPIOA_CRL    *(volatile uint32_t*)(GPIOA_BASE + 0x00)	/* Port configuration register low */
#define GPIOA_CRH    *(volatile uint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR    *(volatile uint32_t*)(GPIOA_BASE + 0x0C)
/* EXTI */
#define EXTI_BASE	 0x40010400
#define EXTI_IMR	 *(volatile uint32_t*)(EXTI_BASE + 0x00)		/* Interrupt mask register */
#define EXTI_RTSR	 *(volatile uint32_t*)(EXTI_BASE + 0x08)		/* Rising trigger selection register */
#define EXTI_FTSR	 *(volatile uint32_t*)(EXTI_BASE + 0x0C)		/* Falling trigger selection register */
#define EXTI_PR		 *(volatile uint32_t*)(EXTI_BASE + 0x14)		/* Pending register */
/* AFIO */
#define AFIO_BASE    0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t*)(AFIO_BASE + 0x08)


void GPIOA_Pin0_Input_init (void)
{
	/* Floating input pin (reset state) */
	GPIOA_CRL |= (1 << 2);
}

void GPIOA_Pin13_Output_init (void)
{
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
}

void EXTI_Init (void)
{
	AFIO_EXTICR1 = 0x0;	    /* Select PA0 for EXTI0 */
	EXTI_RTSR |= 0x1;	    /* Enable rising edge trigger for line 0 */
	//EXTI_FTSR |= 0x1;	    /* Enable falling edge trigger for line 0 */
	EXTI_IMR |= 0x1;	    /* Enable EXTI line 0 */
	NVIC_ISER0 |= (1 << 6);	    /* Enable interrupt 0 in NVIC */
}

void Clock_Init (void)
{
	/* GPIOA clock enable */
	RCC_APB2ENR |= (1 << 2);
	/* AFIO clock enable */
	RCC_APB2ENR |= (1 << 0);
}

void EXTI0_IRQHandler (void)
{
	/* IRQ happened EXTI0 >> PortA.0 >> Rising edge */
	/* Toggle LED >> PINA.13 */
	GPIOA_ODR ^= (1 << 13);

	/* Clear EXTI_PR to avoid infinite interrupt request, by writing '1' */
	EXTI_PR |= 0x1;
}

int main(void)
{
	Clock_Init ();
	GPIOA_Pin0_Input_init ();
	GPIOA_Pin13_Output_init ();
	EXTI_Init ();

	while(1);
}
